### ISSUE TITLE
no resoultion in callback function

### ISSUE THREAD

**Issue by DerT94** [iobroker-community-adapters/ioBroker.telegram#195]
**Describe the bug**  
The "res" variable in the callback function is 0.

**To Reproduce**  
Use this code to send a message.

```
    sendTo('telegram.0', {text:"test", user:"Thomas"}, function(res) {
        console.log('Sent to ' + res + ' users');
    });
```
The log says "Sent to 0 users"

**Expected behavior**  
The log should say "Sent to 1 users"

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
![image](https://user-images.githubusercontent.com/58786605/100436117-35793000-309f-11eb-84d0-c76e1b617b72.png)

**Versions:**  
 - Adapter version: 1.6.0
 - JS-Controller version: 3.1.6
 - Node version: 12.19.0
 - Operating system: Ubuntu 20.04.1 LTS

**Comment by Apollon77** [comment]
callback is alwys called now

**Comment by Nahasapeemapetilon** [comment]
I would like to test the fix where can I find it is it in the trunk?

**Comment by Apollon77** [comment]
ooh sorry ... I was confusing it with an other adapter. sorry

**Comment by Apollon77** [comment]
can you please send a debug log from telegram adapter for such an action?

**Comment by Nahasapeemapetilon** [comment]
i already searched for the bug we have to give _sendMessageHelper and sendMessage a promise, it should look like this otherwise the counter won't work which is returned in the callback 
the functions are very extensive and i have only reworked one place so far:

in _sendhelpmessage  i add one promise for example ::

![image](https://user-images.githubusercontent.com/16188935/109392052-480f3980-791a-11eb-80d6-abaafc2de54e.png)

and in the sendMessage  i put the return promise from sendMessageHelp in a list and I calculate the counter
![image](https://user-images.githubusercontent.com/16188935/109392099-84429a00-791a-11eb-8ee3-fbca6caa1a1d.png)
 in the processmessage we call the callback only if all promise done :
![image](https://user-images.githubusercontent.com/16188935/109392157-f0bd9900-791a-11eb-8907-742c54ea7460.png)

you would have to revise the entire functions I have made only one place


for testing iobroker had used this code and looked when the counter was 0

    sendTo('telegram.0', {text:"test", user:"ch"}, function(res) {    
        console.log('Sent to ' + res + ' users' );
    });

we have no bugs in the log just the res is 0

**Comment by Apollon77** [comment]
If you have it done for you, can you provide a PR?
