### ISSUE TITLE
Adapter stürzt ab

### ISSUE THREAD

**Issue by fuchs-1978** [iobroker-community-adapters/ioBroker.telegram#841]
Ich habe in regelmäßigen Abständen folgende Meldung:

TypeError: Cannot read properties of undefined (reading 'split') at processMessage (/opt/iobroker/node_modules/iobroker.telegram/main.js:1191:52) at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram/main.js:156:17) at AdapterClass.emit (node:events:519:28) at AdapterClass.emit (node:domain:488:12) at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:10949:34) at Immediate.<anonymous> (file:///opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:381:37) at processImmediate (node:internal/timers:478:21)

**Comment by mcm1957** [comment]
Please fill the form provided when creating a new issue of type bug_:

**Describe the bug**  
A clear and concise description of what the bug is.

**To Reproduce**  
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '...'
3. Scroll down to '....'
4. See error

**Expected behavior**  
A clear and concise description of what you expected to happen.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**  
Add any other context about the problem here.

**Comment by crunchip77** [comment]
Ich habe ebenfalls die Fehlermeldung durch das Upgrade von 3.7.1 auf 3.8.1
`<html>
<body>

telegram.1 | 2024-07-16 21:19:21.031 | info | starting. Version 3.7.1 in /opt/iobroker/node_modules/iobroker.telegram, node: v18.20.4, js-controller: 5.0.19
-- | -- | -- | --
telegram.0 | 2024-07-16 21:19:20.985 | info | starting. Version 3.7.1 in /opt/iobroker/node_modules/iobroker.telegram, node: v18.20.4, js-controller: 5.0.19
host.IoBroker | 2024-07-16 21:19:18.635 | info | iobroker exit 0
host.IoBroker | 2024-07-16 21:19:17.790 | info | instance system.adapter.telegram.1 started with pid 9710
host.IoBroker | 2024-07-16 21:19:17.701 | info | instance system.adapter.telegram.0 started with pid 9703
host.IoBroker | 2024-07-16 21:19:17.457 | info | "system.adapter.telegram.1" enabled
host.IoBroker | 2024-07-16 21:19:17.320 | info | iobroker host.IoBroker Adapter "system.adapter.telegram.1" is started
host.IoBroker | 2024-07-16 21:19:17.294 | info | "system.adapter.telegram.0" enabled
host.IoBroker | 2024-07-16 21:19:17.283 | info | iobroker host.IoBroker Adapter "system.adapter.telegram.0" is started
host.IoBroker | 2024-07-16 21:19:17.275 | info | iobroker upload [0] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/telegram.png telegram.png image/png
host.IoBroker | 2024-07-16 21:19:17.269 | info | iobroker upload [1] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/src_bootstrap_jsx.daa4bc6c.chunk.js.map rules/static/js/src_bootstrap_jsx.daa4bc6c.chunk.js.map application/json
host.IoBroker | 2024-07-16 21:19:17.255 | info | iobroker upload [2] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/src_bootstrap_jsx.daa4bc6c.chunk.js rules/static/js/src_bootstrap_jsx.daa4bc6c.chunk.js application/javascript
host.IoBroker | 2024-07-16 21:19:17.247 | info | iobroker upload [3] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/src_ActionTelegram_jsx.606264b1.chunk.js.map rules/static/js/src_ActionTelegram_jsx.606264b1.chunk.js.map application/json
host.IoBroker | 2024-07-16 21:19:17.235 | info | iobroker upload [4] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/src_ActionTelegram_jsx.606264b1.chunk.js rules/static/js/src_ActionTelegram_jsx.606264b1.chunk.js application/javascript
host.IoBroker | 2024-07-16 21:19:17.230 | info | iobroker upload [5] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/node_modules_react_index_js.6114a944.chunk.js.map rules/static/js/node_modules_react_index_js.6114a944.chunk.js.map application/json
host.IoBroker | 2024-07-16 21:19:17.225 | info | iobroker upload [6] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/node_modules_react_index_js.6114a944.chunk.js rules/static/js/node_modules_react_index_js.6114a944.chunk.js application/javascript
host.IoBroker | 2024-07-16 21:19:17.220 | info | iobroker upload [7] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/node_modules_prop-types_index_js.c5b5d86f.chunk.js.map rules/static/js/node_modules_prop-types_index_js.c5b5d86f.chunk.js.map application/json
host.IoBroker | 2024-07-16 21:19:17.217 | info | iobroker upload [8] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/node_modules_prop-types_index_js.c5b5d86f.chunk.js rules/static/js/node_modules_prop-types_index_js.c5b5d86f.chunk.js application/javascript
host.IoBroker | 2024-07-16 21:19:17.214 | info | iobroker upload [9] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/node_modules_iobroker_adapter-react-v5_node_modules_react_index_js-_9d271.bbc6ce97.chunk.js.map rules/static/js/node_modules_iobroker_adapter-react-v5_node_modules_react_index_js-_9d271.bbc6ce97.chunk.js.map application/json
host.IoBroker | 2024-07-16 21:19:17.212 | info | iobroker upload [10] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/node_modules_iobroker_adapter-react-v5_node_modules_react_index_js-_9d271.bbc6ce97.chunk.js rules/static/js/node_modules_iobroker_adapter-react-v5_node_modules_react_index_js-_9d271.bbc6ce97.chunk.js application/javascript
host.IoBroker | 2024-07-16 21:19:17.209 | info | iobroker upload [11] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/node_modules_iobroker_adapter-react-v5_node_modules_react_index_js-_9d270.bc9865f0.chunk.js.map rules/static/js/node_modules_iobroker_adapter-react-v5_node_modules_react_index_js-_9d270.bc9865f0.chunk.js.map application/json
host.IoBroker | 2024-07-16 21:19:17.206 | info | iobroker upload [12] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/node_modules_iobroker_adapter-react-v5_node_modules_react_index_js-_9d270.bc9865f0.chunk.js rules/static/js/node_modules_iobroker_adapter-react-v5_node_modules_react_index_js-_9d270.bc9865f0.chunk.js application/javascript
host.IoBroker | 2024-07-16 21:19:17.203 | info | iobroker upload [13] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/node_modules_iobroker_adapter-react-v5_assets_devices_sync_recursive_-node_modules_iobroker_a-d234ae.c537ddf6.chunk.js.map rules/static/js/node_modules_iobroker_adapter-react-v5_assets_devices_sync_recursive_-node_modules_iobroker_a-d234ae.c537ddf6.chunk.js.map application/json
host.IoBroker | 2024-07-16 21:19:17.200 | info | iobroker upload [14] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/node_modules_iobroker_adapter-react-v5_assets_devices_sync_recursive_-node_modules_iobroker_a-d234ae.c537ddf6.chunk.js rules/static/js/node_modules_iobroker_adapter-react-v5_assets_devices_sync_recursive_-node_modules_iobroker_a-d234ae.c537ddf6.chunk.js application/javascript
host.IoBroker | 2024-07-16 21:19:17.198 | info | iobroker upload [15] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/main.44f1f861.js.map rules/static/js/main.44f1f861.js.map application/json
host.IoBroker | 2024-07-16 21:19:17.195 | info | iobroker upload [16] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/static/js/main.44f1f861.js rules/static/js/main.44f1f861.js application/javascript
host.IoBroker | 2024-07-16 21:19:17.192 | info | iobroker upload [17] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/i18n/zh-cn.json rules/i18n/zh-cn.json application/json
host.IoBroker | 2024-07-16 21:19:17.190 | info | iobroker upload [18] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/i18n/uk.json rules/i18n/uk.json application/json
host.IoBroker | 2024-07-16 21:19:17.187 | info | iobroker upload [19] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/i18n/ru.json rules/i18n/ru.json application/json
host.IoBroker | 2024-07-16 21:19:17.184 | info | iobroker upload [20] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/i18n/pt.json rules/i18n/pt.json application/json
host.IoBroker | 2024-07-16 21:19:17.149 | info | iobroker upload [30] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/rules/asset-manifest.json rules/asset-manifest.json application/json
host.IoBroker | 2024-07-16 21:19:17.129 | info | iobroker upload [40] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
host.IoBroker | 2024-07-16 21:19:17.107 | info | iobroker upload [50] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/custom/static/js/node_modules_prop-types_index_js.6da256b6.chunk.js.map custom/static/js/node_modules_prop-types_index_js.6da256b6.chunk.js.map application/json
host.IoBroker | 2024-07-16 21:19:17.085 | info | iobroker upload [60] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/custom/static/js/node_modules_iobroker_adapter-react-v5_assets_devices_sync_recursive_-node_modules_iobroker_a-de23731.0f3598f3.chunk.js.map custom/static/js/node_modules_iobroker_adapter-react-v5_assets_devices_sync_recursive_-node_modules_iobroker_a-de23731.0f3598f3.chunk.js.map application/json
host.IoBroker | 2024-07-16 21:19:17.063 | info | iobroker upload [70] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/custom/i18n/pl.json custom/i18n/pl.json application/json
host.IoBroker | 2024-07-16 21:19:17.044 | info | iobroker upload [79] telegram.admin /opt/iobroker/node_modules/iobroker.telegram/admin/blockly.js blockly.js application/javascript
host.IoBroker | 2024-07-16 21:19:16.565 | info | iobroker Update "system.adapter.telegram.1"
host.IoBroker | 2024-07-16 21:19:16.526 | info | iobroker Update "system.adapter.telegram.0"
host.IoBroker | 2024-07-16 21:19:16.439 | info | iobroker 332 packages are looking for funding run `npm fund` for details
host.IoBroker | 2024-07-16 21:19:16.439 | info | iobroker changed 1 package in 5s
host.IoBroker | 2024-07-16 21:19:12.243 | info | instance system.adapter.telegram.1 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.IoBroker | 2024-07-16 21:19:12.117 | info | instance system.adapter.telegram.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.IoBroker | 2024-07-16 21:19:12.096 | info | stopInstance system.adapter.telegram.1 killing pid 9569
host.IoBroker | 2024-07-16 21:19:12.033 | info | stopInstance system.adapter.telegram.0 killing pid 9586
telegram.1 | 2024-07-16 21:19:11.572 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
telegram.1 | 2024-07-16 21:19:11.572 | info | terminating
telegram.0 | 2024-07-16 21:19:11.516 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
telegram.0 | 2024-07-16 21:19:11.516 | info | terminating
host.IoBroker | 2024-07-16 21:19:11.166 | info | iobroker NPM version: 10.8.1Installing iobroker.telegram@3.7.1... (System call)
host.IoBroker | 2024-07-16 21:19:11.092 | info | stopInstance system.adapter.telegram.1 send kill signal
telegram.1 | 2024-07-16 21:19:11.071 | info | Got terminate signal TERMINATE_YOURSELF
host.IoBroker | 2024-07-16 21:19:11.032 | info | stopInstance system.adapter.telegram.0 send kill signal
host.IoBroker | 2024-07-16 21:19:11.031 | info | stopInstance system.adapter.telegram.1 (force=false, process=true)
host.IoBroker | 2024-07-16 21:19:11.031 | info | "system.adapter.telegram.1" disabled
telegram.0 | 2024-07-16 21:19:11.015 | info | Got terminate signal TERMINATE_YOURSELF
host.IoBroker | 2024-07-16 21:19:11.011 | info | iobroker host.IoBroker Adapter "system.adapter.telegram.1" is stopped.
host.IoBroker | 2024-07-16 21:19:10.935 | info | stopInstance system.adapter.telegram.0 (force=false, process=true)
host.IoBroker | 2024-07-16 21:19:10.934 | info | "system.adapter.telegram.0" disabled
host.IoBroker | 2024-07-16 21:19:10.920 | info | iobroker host.IoBroker Adapter "system.adapter.telegram.0" is stopped.
host.IoBroker | 2024-07-16 21:19:10.892 | info | iobroker Update telegram from @3.8.1 to @3.7.1
host.IoBroker | 2024-07-16 21:19:09.261 | info | iobroker upgrade telegram@3.7.1 --debug
telegram.0 | 2024-07-16 21:10:43.710 | info | starting. Version 3.8.1 in /opt/iobroker/node_modules/iobroker.telegram, node: v18.20.4, js-controller: 5.0.19
host.IoBroker | 2024-07-16 21:10:41.376 | info | instance system.adapter.telegram.0 started with pid 9586
telegram.1 | 2024-07-16 21:10:14.636 | info | starting. Version 3.8.1 in /opt/iobroker/node_modules/iobroker.telegram, node: v18.20.4, js-controller: 5.0.19
host.IoBroker | 2024-07-16 21:10:12.236 | info | instance system.adapter.telegram.1 started with pid 9569
host.IoBroker | 2024-07-16 21:10:11.279 | info | Restart adapter system.adapter.telegram.0 because enabled
host.IoBroker | 2024-07-16 21:10:11.279 | error | instance system.adapter.telegram.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.IoBroker | 2024-07-16 21:10:11.279 | error | Caught by controller[1]: at processImmediate (node:internal/timers:476:21)
host.IoBroker | 2024-07-16 21:10:11.279 | error | Caught by controller[1]: at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:379:37)
host.IoBroker | 2024-07-16 21:10:11.279 | error | Caught by controller[1]: at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11114:34)
host.IoBroker | 2024-07-16 21:10:11.279 | error | Caught by controller[1]: at AdapterClass.emit (node:domain:489:12)
host.IoBroker | 2024-07-16 21:10:11.279 | error | Caught by controller[1]: at AdapterClass.emit (node:events:517:28)
host.IoBroker | 2024-07-16 21:10:11.279 | error | Caught by controller[1]: at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram/main.js:156:17)
host.IoBroker | 2024-07-16 21:10:11.279 | error | Caught by controller[1]: at processMessage (/opt/iobroker/node_modules/iobroker.telegram/main.js:1191:52)
host.IoBroker | 2024-07-16 21:10:11.279 | error | Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'split')
host.IoBroker | 2024-07-16 21:10:11.279 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
telegram.0 | 2024-07-16 21:10:10.696 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
telegram.0 | 2024-07-16 21:10:10.695 | info | terminating
telegram.0 | 2024-07-16 21:10:10.188 | error | Cannot read properties of undefined (reading 'split')
telegram.0 | 2024-07-16 21:10:10.187 | error | TypeError: Cannot read properties of undefined (reading 'split') at processMessage (/opt/iobroker/node_modules/iobroker.telegram/main.js:1191:52) at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram/main.js:156:17) at AdapterClass.emit (node:events:517:28) at AdapterClass.emit (node:domain:489:12) at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11114:34) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:379:37) at processImmediate (node:internal/timers:476:21)
host.IoBroker | 2024-07-16 21:10:10.129 | info | instance system.adapter.telegram.1 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
telegram.0 | 2024-07-16 21:10:10.115 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'split')
telegram.0 | 2024-07-16 21:10:10.115 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
telegram.1 | 2024-07-16 21:10:09.554 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
telegram.1 | 2024-07-16 21:10:09.554 | info | terminating
host.IoBroker | 2024-07-16 21:10:09.147 | info | stopInstance system.adapter.telegram.1 send kill signal
telegram.1 | 2024-07-16 21:10:09.051 | info | Got terminate signal TERMINATE_YOURSELF
host.IoBroker | 2024-07-16 21:10:09.027 | info | stopInstance system.adapter.telegram.1 (force=false, process=true)
telegram.0 | 2024-07-16 21:08:58.618 | info | starting. Version 3.8.1 in /opt/iobroker/node_modules/iobroker.telegram, node: v18.20.4, js-controller: 5.0.19
host.IoBroker | 2024-07-16 21:08:56.292 | info | instance system.adapter.telegram.0 started with pid 9546
host.IoBroker | 2024-07-16 21:08:54.211 | info | instance system.adapter.telegram.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
telegram.0 | 2024-07-16 21:08:53.636 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
telegram.0 | 2024-07-16 21:08:53.635 | info | terminating
host.IoBroker | 2024-07-16 21:08:53.185 | info | stopInstance system.adapter.telegram.0 send kill signal
telegram.0 | 2024-07-16 21:08:53.134 | info | Got terminate signal TERMINATE_YOURSELF
host.IoBroker | 2024-07-16 21:08:53.056 | info | stopInstance system.adapter.telegram.0 (force=false, process=true)
javascript.0 | 2024-07-16 21:08:01.451 | info | script.js.Statusmeldungen.Status_Lichtzählen1: Text: Esstisch
javascript.0 | 2024-07-16 21:06:42.869 | info | script.js.Statusmeldungen.Status_Lichtzählen1: Text: Esstisch ,Kueche
telegram.0 | 2024-07-16 21:01:01.860 | info | starting. Version 3.8.1 in /opt/iobroker/node_modules/iobroker.telegram, node: v18.20.4, js-controller: 5.0.19
host.IoBroker | 2024-07-16 21:00:59.292 | info | instance system.adapter.telegram.0 started with pid 9483
host.IoBroker | 2024-07-16 21:00:30.487 | info | instance system.adapter.mqtt.0 started with pid 9464
host.IoBroker | 2024-07-16 21:00:29.178 | info | Restart adapter system.adapter.telegram.0 because enabled
host.IoBroker | 2024-07-16 21:00:29.178 | error | instance system.adapter.telegram.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.IoBroker | 2024-07-16 21:00:29.178 | error | Caught by controller[0]: at processImmediate (node:internal/timers:476:21)
host.IoBroker | 2024-07-16 21:00:29.178 | error | Caught by controller[0]: at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:379:37)
host.IoBroker | 2024-07-16 21:00:29.177 | error | Caught by controller[0]: at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11114:34)
host.IoBroker | 2024-07-16 21:00:29.177 | error | Caught by controller[0]: at AdapterClass.emit (node:domain:489:12)
host.IoBroker | 2024-07-16 21:00:29.177 | error | Caught by controller[0]: at AdapterClass.emit (node:events:517:28)
host.IoBroker | 2024-07-16 21:00:29.177 | error | Caught by controller[0]: at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram/main.js:156:17)
host.IoBroker | 2024-07-16 21:00:29.177 | error | Caught by controller[0]: at processMessage (/opt/iobroker/node_modules/iobroker.telegram/main.js:1191:52)
host.IoBroker | 2024-07-16 21:00:29.177 | error | Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'split')
host.IoBroker | 2024-07-16 21:00:29.177 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
host.IoBroker | 2024-07-16 21:00:28.606 | info | iobroker exit 0
telegram.0 | 2024-07-16 21:00:28.600 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
telegram.0 | 2024-07-16 21:00:28.599 | info | terminating
telegram.0 | 2024-07-16 21:00:28.014 | error | Cannot read properties of undefined (reading 'split')
telegram.0 | 2024-07-16 21:00:28.014 | error | TypeError: Cannot read properties of undefined (reading 'split') at processMessage (/opt/iobroker/node_modules/iobroker.telegram/main.js:1191:52) at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.telegram/main.js:156:17) at AdapterClass.emit (node:events:517:28) at AdapterClass.emit (node:domain:489:12) at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11114:34) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:379:37) at processImmediate (node:internal/timers:476:21)
host.IoBroker | 2024-07-16 21:00:27.942 | info | instance system.adapter.mqtt.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
telegram.0 | 2024-07-16 21:00:27.928 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'split')
telegram.0 | 2024-07-16 21:00:27.927 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


</body>
</html>`
`CPU: 40 %
RAM: 40 %
Betriebszeit: 18h
Verfügbar: 6.0.8
Installiert: 5.0.19
Ereignisse: ⇥45 / ↦13
Plattform: docker (official image - v9.1.2)
Betriebssystem: linux
Architektur: x64
CPUs: 16
Geschwindigkeit: 3695 MHz
Modell: AMD Ryzen 9 6900HX with Radeon Graphics
RAM: 30.6 GB
System-Betriebszeit: 9 T. 10:00:11
Node.js: v18.20.4
time: 1721156190271
timeOffset: -120
NPM: 10.8.1
Adapter-Anzahl: 624
Datenträgergröße: 953.9 GB
Freier Festplattenspeicher: 642.7 GB
Aktive Instanzen: 45
Pfad: /opt/iobroker/
Betriebszeit: 17:54:47`

**Comment by mcm1957** [comment]
Please retest eith newest release (3.8.2)

If problem still exidzs please add complete version infos
Adapter
Admin
Js-controller
Node
O/S

**Comment by fuchs-1978** [comment]
Mit der neuen Version tritt es nicht mehr auf

**Comment by tmaul1968** [comment]
Sounds great that 3.8.2 solves the problem.
I got the same problem with 3.8.1 and rolled back to 3.8.0 which workes fine for me.

I use the beta repository and there is no 3.8.2. Where may I find this to test if it fixes the problem in my environment?
Cheers, Thomas

**Comment by mcm1957** [comment]
So I will close here.
Please open a new issue if problem reoccures
